# Generated by Django 4.0.6 on 2022-09-04 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Área de Especialidad')),
                ('abreviatura', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Area de Especialidad',
                'verbose_name_plural': 'Areas de Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Categoría')),
                ('abreviatura', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Centro de Trabajo',
                'verbose_name_plural': 'Centros de Trabajos',
            },
        ),
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Conocimiento',
                'verbose_name_plural': 'Conocimientos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='RolTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=350)),
                ('area_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.areaespecialidad')),
                ('conocimientos', models.ManyToManyField(to='Sistema.conocimiento', verbose_name='Lista de Conocimientos')),
                ('habilidades', models.ManyToManyField(to='Sistema.habilidad', verbose_name='Lista de Habilidades')),
                ('herramientas', models.ManyToManyField(to='Sistema.herramienta', verbose_name='Lista de Herramientas')),
                ('tareas', models.ManyToManyField(to='Sistema.tarea', verbose_name='Lista de Tareas')),
            ],
            options={
                'verbose_name': 'Rol de Trabajo',
                'verbose_name_plural': 'Roles de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.validate_integer])),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('conocimientos', models.ManyToManyField(to='Sistema.conocimiento')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.genero')),
                ('habilidades', models.ManyToManyField(to='Sistema.habilidad')),
                ('herramientas', models.ManyToManyField(to='Sistema.herramienta')),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sistema.municipio')),
                ('provincia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sistema.provincia')),
                ('tareas', models.ManyToManyField(to='Sistema.tarea')),
                ('trabajo_antiguos', models.ManyToManyField(to='Sistema.centrotrabajo', verbose_name='Centros de Trabajo Previos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
        ),
        migrations.AddField(
            model_name='areaespecialidad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.categoria'),
        ),
    ]
