# Generated by Django 4.0.6 on 2022-09-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_remove_genero_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='avatar',
            field=models.ImageField(default='', upload_to='Sistema'),
            preserve_default=False,
        ),
    ]
