# Generated by Django 4.0.6 on 2022-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_alter_especialista_trabajo_antiguos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Sistema'),
        ),
    ]
