# Generated by Django 4.0.6 on 2022-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0007_alter_especialista_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='conocimientos',
            field=models.ManyToManyField(blank=True, null=True, to='Sistema.conocimiento'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, to='Sistema.habilidad'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='herramientas',
            field=models.ManyToManyField(blank=True, null=True, to='Sistema.herramienta'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='tareas',
            field=models.ManyToManyField(blank=True, null=True, to='Sistema.tarea'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='trabajo_antiguos',
            field=models.ManyToManyField(blank=True, null=True, to='Sistema.centrotrabajo', verbose_name='Centros de Trabajo Previos'),
        ),
    ]
