# Generated by Django 4.0.6 on 2022-09-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_especialista_fecha_nacimiento_alter_especialista_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='fecha_nacimiento',
        ),
    ]
