# Generated by Django 4.0.6 on 2022-09-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0016_alter_especialista_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Sistema/UsersAvatars'),
        ),
    ]
