# Generated by Django 4.0.6 on 2022-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0018_alter_especialista_conocimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
